# Generated by Django 4.2.1 on 2023-06-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSearchRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want', models.TextField()),
                ('have', models.TextField()),
                ('request_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type_id', models.CharField(max_length=200)),
                ('item_type_label', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_type', models.CharField(max_length=200, null=True)),
                ('item_text', models.CharField(max_length=200, null=True)),
                ('item_json_flags', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=400)),
                ('item_name', models.CharField(max_length=400)),
                ('image_url', models.TextField()),
                ('item_tag', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=200)),
                ('league_realm', models.CharField(max_length=200)),
                ('league_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchesJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_url', models.CharField(max_length=2000)),
                ('search_json', models.TextField()),
                ('response_json', models.TextField()),
                ('search_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_stat_id', models.CharField(max_length=200)),
                ('search_stat_label', models.CharField(max_length=200)),
                ('stat_id', models.CharField(max_length=200)),
                ('stat_text', models.CharField(max_length=200)),
                ('stat_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_type_id', models.CharField(max_length=200)),
                ('static_type_label', models.CharField(max_length=200)),
                ('static_id', models.CharField(max_length=200)),
                ('static_text', models.CharField(max_length=200)),
                ('static_image_url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultsJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_url', models.TextField()),
                ('response_json', models.TextField()),
                ('result_datetime', models.DateTimeField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apollo.searchesjson')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSearchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=400)),
                ('search_datetime', models.DateTimeField()),
                ('price_type', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price_rank', models.IntegerField()),
                ('account_name', models.CharField(max_length=200)),
                ('source_search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apollo.searchresultsjson')),
            ],
        ),
        migrations.CreateModel(
            name='BulkSearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=400)),
                ('last_character_name', models.CharField(max_length=400)),
                ('offer_tag', models.CharField(max_length=200)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('for_tag', models.CharField(max_length=200)),
                ('for_amount', models.IntegerField()),
                ('for_stock', models.IntegerField()),
                ('whisper', models.TextField()),
                ('source_search_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apollo.bulksearchrequests')),
            ],
        ),
    ]
