# Generated by Django 4.2.1 on 2023-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apollo', '0002_bulksearchresults_result_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static',
            name='static_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='static_image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='static_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='static_type_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='static',
            name='static_type_label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
